// <auto-generated />
using System;
using AtendimentoMultiTenant.Infra.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AtendimentoMultiTenant.Infra.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AtendimentoMultiTenant.Core.Entities.ConfigurationEntities.ContainerDb", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<DateOnly?>("ContainerDbCreatedAt")
                        .HasColumnType("date")
                        .HasColumnName("container_db_created_at");

                    b.Property<string>("ContainerDbImage")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("container_db_image");

                    b.Property<string>("ContainerDbName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("container_db_name");

                    b.Property<string>("ContainerDbNetwork")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("container_db_network");

                    b.Property<string>("ContainerDbPort")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)")
                        .HasColumnName("container_db_port");

                    b.Property<string>("ContainerDbVolume")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("container_db_volume");

                    b.Property<string>("EnvironmentDbName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("environment_db_name");

                    b.Property<string>("EnvironmentDbPwd")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("environment_db_pwd");

                    b.Property<string>("EnvironmentDbUser")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("environment_db_user");

                    b.Property<bool>("IsUp")
                        .HasColumnType("boolean")
                        .HasColumnName("is_up");

                    b.Property<Guid>("PortId")
                        .HasColumnType("uuid")
                        .HasColumnName("port_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("PortId");

                    b.HasIndex("TenantId");

                    b.ToTable("ContainerDb", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("f35a4eae-6eee-49e4-95a0-3df60e6ca9b0"),
                            ContainerDbImage = "postgres:16.2",
                            ContainerDbName = "postgresql_cliente1",
                            ContainerDbNetwork = "cliente1_network",
                            ContainerDbPort = "5434",
                            ContainerDbVolume = "cliente1_volume",
                            EnvironmentDbName = "Cliente1DB",
                            EnvironmentDbPwd = "pwdcliente1",
                            EnvironmentDbUser = "usercliente1",
                            IsUp = false,
                            PortId = new Guid("f35a4eae-6eee-49e4-95a0-3df60e6ca9b0"),
                            TenantId = new Guid("f6a2372a-b146-45f9-be70-a0be13736dd8")
                        },
                        new
                        {
                            Id = new Guid("62afeccd-c9bb-48b2-a60b-0c5fe2b38694"),
                            ContainerDbImage = "postgres:16.2",
                            ContainerDbName = "postgresql_cliente2",
                            ContainerDbNetwork = "cliente2_network",
                            ContainerDbPort = "5435",
                            ContainerDbVolume = "cliente2_volume",
                            EnvironmentDbName = "Cliente2DB",
                            EnvironmentDbPwd = "pwdcliente2",
                            EnvironmentDbUser = "usercliente2",
                            IsUp = false,
                            PortId = new Guid("62afeccd-c9bb-48b2-a60b-0c5fe2b38694"),
                            TenantId = new Guid("64210b12-a8d4-44ae-b35e-b13b762c4179")
                        },
                        new
                        {
                            Id = new Guid("39715917-a829-41c4-8da1-64029a0c6364"),
                            ContainerDbImage = "postgres:16.2",
                            ContainerDbName = "postgresql_cliente3",
                            ContainerDbNetwork = "cliente3_network",
                            ContainerDbPort = "5436",
                            ContainerDbVolume = "cliente3_volume",
                            EnvironmentDbName = "Cliente3DB",
                            EnvironmentDbPwd = "pwdcliente3",
                            EnvironmentDbUser = "usercliente3",
                            IsUp = false,
                            PortId = new Guid("39715917-a829-41c4-8da1-64029a0c6364"),
                            TenantId = new Guid("25ae8570-56b6-4a9d-9616-c15862613525")
                        });
                });

            modelBuilder.Entity("AtendimentoMultiTenant.Core.Entities.ConfigurationEntities.Port", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<string>("PortNumber")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)")
                        .HasColumnName("port_number");

                    b.HasKey("Id");

                    b.ToTable("Port", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("f35a4eae-6eee-49e4-95a0-3df60e6ca9b0"),
                            PortNumber = "5434"
                        },
                        new
                        {
                            Id = new Guid("62afeccd-c9bb-48b2-a60b-0c5fe2b38694"),
                            PortNumber = "5435"
                        },
                        new
                        {
                            Id = new Guid("39715917-a829-41c4-8da1-64029a0c6364"),
                            PortNumber = "5436"
                        });
                });

            modelBuilder.Entity("AtendimentoMultiTenant.Core.Entities.ConfigurationEntities.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<string>("ConnectionString")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("connection_string");

                    b.Property<string>("InitialUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("initial_url");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.Property<string>("Secret")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("secret");

                    b.HasKey("Id");

                    b.ToTable("Tenant", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("f6a2372a-b146-45f9-be70-a0be13736dd8"),
                            ConnectionString = "Host=localhost;Port=5433;Database=Cliente1DB;User ID=usercliente1;Password=pwdcliente1;Pooling=true;",
                            InitialUrl = "",
                            IsActive = true,
                            Name = "Cliente1",
                            Secret = "123"
                        },
                        new
                        {
                            Id = new Guid("64210b12-a8d4-44ae-b35e-b13b762c4179"),
                            ConnectionString = "Host=localhost;Port=5434;Database=Cliente2DB;User ID=usercliente2;Password=pwdcliente2;Pooling=true;",
                            InitialUrl = "",
                            IsActive = true,
                            Name = "Cliente2",
                            Secret = "123"
                        },
                        new
                        {
                            Id = new Guid("25ae8570-56b6-4a9d-9616-c15862613525"),
                            ConnectionString = "Host=localhost;Port=5435;Database=Cliente3DB;User ID=usercliente3;Password=pwdcliente3;Pooling=true;",
                            InitialUrl = "",
                            IsActive = true,
                            Name = "Cliente3",
                            Secret = "123"
                        });
                });

            modelBuilder.Entity("AtendimentoMultiTenant.Core.Entities.ConfigurationEntities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("email");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("password");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid?>("UserTokenId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_token_id");

                    b.Property<Guid?>("UserTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_type_id");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("user_email");

                    b.HasIndex("TenantId");

                    b.HasIndex("UserTokenId");

                    b.HasIndex("UserTypeId");

                    b.ToTable("User", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("60a52233-dbd8-426d-8724-38dcedaa24d9"),
                            Email = "admin1@teste.com",
                            IsActive = true,
                            Name = "admin",
                            Password = "123",
                            TenantId = new Guid("f6a2372a-b146-45f9-be70-a0be13736dd8"),
                            UserTypeId = new Guid("45533ff6-3ba5-11ef-9476-0242ac130002")
                        },
                        new
                        {
                            Id = new Guid("4214fa3a-91a6-41a7-b2ab-e39be9ef5128"),
                            Email = "cliente1@teste.com",
                            IsActive = true,
                            Name = "cliente1",
                            Password = "123",
                            TenantId = new Guid("64210b12-a8d4-44ae-b35e-b13b762c4179"),
                            UserTypeId = new Guid("6c9b91d0-3ba5-11ef-9476-0242ac130002")
                        },
                        new
                        {
                            Id = new Guid("806a18fa-a650-446b-bb9f-4cb495ba0533"),
                            Email = "cliente2@teste.com",
                            IsActive = true,
                            Name = "cliente2",
                            Password = "123",
                            TenantId = new Guid("25ae8570-56b6-4a9d-9616-c15862613525"),
                            UserTypeId = new Guid("6c9b91d0-3ba5-11ef-9476-0242ac130002")
                        });
                });

            modelBuilder.Entity("AtendimentoMultiTenant.Core.Entities.ConfigurationEntities.UserToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<DateTime>("Expiration")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expiration");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("token");

                    b.HasKey("Id");

                    b.ToTable("UserToken", (string)null);
                });

            modelBuilder.Entity("AtendimentoMultiTenant.Core.Entities.ConfigurationEntities.UserType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("UserType", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("45533ff6-3ba5-11ef-9476-0242ac130002"),
                            Name = "Administrador"
                        },
                        new
                        {
                            Id = new Guid("6c9b91d0-3ba5-11ef-9476-0242ac130002"),
                            Name = "Cliente"
                        });
                });

            modelBuilder.Entity("AtendimentoMultiTenant.Core.Entities.ConfigurationEntities.ContainerDb", b =>
                {
                    b.HasOne("AtendimentoMultiTenant.Core.Entities.ConfigurationEntities.Port", "Port")
                        .WithMany()
                        .HasForeignKey("PortId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AtendimentoMultiTenant.Core.Entities.ConfigurationEntities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Port");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("AtendimentoMultiTenant.Core.Entities.ConfigurationEntities.User", b =>
                {
                    b.HasOne("AtendimentoMultiTenant.Core.Entities.ConfigurationEntities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AtendimentoMultiTenant.Core.Entities.ConfigurationEntities.UserToken", "UserToken")
                        .WithMany()
                        .HasForeignKey("UserTokenId");

                    b.HasOne("AtendimentoMultiTenant.Core.Entities.ConfigurationEntities.UserType", "UserType")
                        .WithMany()
                        .HasForeignKey("UserTypeId");

                    b.Navigation("Tenant");

                    b.Navigation("UserToken");

                    b.Navigation("UserType");
                });
#pragma warning restore 612, 618
        }
    }
}
