namespace AtendimentoMultiTenant.Shared.CommonArea.Enumerators
{
    public enum RoutesEnumerator
    {
        [Description("/error")]
        Error,
        [Description("/")]
        Index,
        [Description("/login")]
        Login,
        [Description("/configdashboard")]
        Dashboard,
        [Description("/containers")]
        Containers,
        [Description("/containerdetail")]
        ContainerDetail,
        [Description("/logs")]
        Logs,
        [Description("/menus")]
        Menus,
        [Description("/menudetail")]
        MenuDetail,
        [Description("/features")]
        Features,
        [Description("/featuredetail")]
        FeatureDetail,
        [Description("/roles")]
        Roles,
        [Description("/roledetail")]
        RoleDetail,
        [Description("/tenants")]
        Tenants,
        [Description("/tenantdetail")]
        TenantDetail,
        [Description("/users")]
        Users,
        [Description("/userdetail")]
        UserDetail,
    }
}
